---
apiVersion: v1
kind: Pod
metadata:
  name: tomcatpod
  labels:
    app: dockerhub

spec:
  containers:
  - name: tom-cont
    image: tomcat
    env:
    - name: fristname
      value: "srikanth"
    command: [ 'sh', '-c', 'echo the app is running! && sleep 3600' ]
